### ISSUE TITLE
Error: Canot find module './lang/clone' 

### ISSUE THREAD

**Issue by dannyphung** [bower/bower#1859]
I get this error on any bower command after update to 1.4.1. My OS is Ubuntu 15

```
$: bower

module.js:340
    throw err;
          ^
Error: Cannot find module './lang/clone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/bower-config/node_modules/mout/lang.js:6:15)
```

**Comment by sheerun** [comment]
Sorry, no idea what went wrong. It seems like npm / node issue, though.

Let me know if you find a way to reproduce.

E.g. what files are in /usr/local/lib/node_modules/bower/node_modules/bower-config/node_modules/mout

**Comment by dannyphung** [comment]
I got no folder named "lang". It seem that cause error. 
hank@hank-Lenovo-G50-70:/usr/local/lib/node_modules/bower/node_modules/bower-config/node_modules/mout$ ll ./lang

**Comment by sheerun** [comment]
Then it's some kind of npm issue. Bower is not responsible for proper installing of its dependencies.
