### ISSUE TITLE
Bower Is not working on 1.6.3

### ISSUE THREAD

**Issue by Danjavia** [bower/bower#1963]
Cannot find module 'escape-string-regexp' error is launched.

This version don't allow search, update or install new packages.

**Comment by sheerun** [comment]
What is your platform / node version / npm version? How did you install bower?

**Comment by Danjavia** [comment]
Running npm install -g bower

I uninstall and reinstall the 1.5.3 version and run perfectly

npm 1.3.14
windows 7 
node 0.10.22

**Comment by damiandennis** [comment]
yeah I am having some issues on 1.6.3, its extracting the packages differently than before. The full folder with the version number is being extracted instead of just the name of the package.

**Comment by sheerun** [comment]
@damiandennis That's another issue I guess.. Can you fill another issue with steps to reproduce?
